// batch-prompt-parity.test.mjs — pins structural agreement between the
// canonical rubric (modes/_shared.md) and the compact batch worker prompt
// (batch/batch-prompt.md).
//
// History: the batch prompt once carried a hand-copied rubric that drifted
// two generations behind _shared.md while keeping a MATCHING scoring-version
// stamp — so the runner's version check passed while workers scored with a
// different framework, auto-generated PDFs, and wrote a wrong-shaped TSV.
// The version stamp only proves someone bumped a comment; these checks prove
// the load-bearing structures actually agree.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const shared = readFileSync(join(ROOT, 'modes/_shared.md'), 'utf8')
const prompt = readFileSync(join(ROOT, 'batch/batch-prompt.md'), 'utf8')
const scouting = readFileSync(join(ROOT, 'modes/scouting.md'), 'utf8')

function versionOf(text) {
  const m = text.match(/<!-- scoring-version: ([0-9-]+) -->/)
  return m ? m[1] : null
}

test('scoring-version stamps match', () => {
  assert.equal(versionOf(prompt), versionOf(shared))
  assert.ok(versionOf(shared), 'shared.md must carry a scoring-version stamp')
})

test('score-history.tsv header line is byte-identical in both files', () => {
  const headerRe = /^date\tarchetype\t.*\turl$/m
  const inShared = shared.match(headerRe)?.[0]
  const inPrompt = prompt.match(headerRe)?.[0]
  assert.ok(inShared, '_shared.md must contain the score-history header')
  assert.ok(inPrompt, 'batch-prompt.md must contain the score-history header')
  assert.equal(inPrompt, inShared)
  assert.equal(inShared.split('\t').length, 26, 'header is 26 columns')
})

test('batch prompt delegates math to score-listing.mjs and states the fixed rollup weights', () => {
  assert.match(prompt, /score-listing\.mjs/)
  assert.match(prompt, /CF × 0\.70 \+ AF × 0\.30/)
  assert.match(shared, /Current Fit × 0\.70 \+ Aspirational Fit × 0\.30/)
})

test('all six scoring dimensions + Sales-Trap exclusion are present', () => {
  for (const dim of [
    'Skills Match', 'Ease of Entry', 'Strategic/Analytical Fit',
    'Growth/Mobility', 'Optionality/Exit', 'Brand Value', 'Sales-Trap Risk',
  ]) {
    assert.ok(prompt.includes(dim), `batch prompt names ${dim}`)
    assert.ok(shared.includes(dim), `_shared.md names ${dim}`)
  }
  assert.match(prompt, /not (?:in|rolled into) the AF rollup/i)
})

test('key Ease-of-Entry calibration constants agree with _shared.md', () => {
  // These are the numbers most likely to silently diverge in a rewrite.
  for (const token of ['£38,700', '−2 to −4', 'CEMS Corporate Partner']) {
    assert.ok(shared.includes(token), `_shared.md contains ${token}`)
    assert.ok(prompt.includes(token), `batch prompt contains ${token}`)
  }
})

test('batch workers write the scouting flow, not the applications tracker', () => {
  assert.match(prompt, /batch\/scouting-additions\//)
  assert.match(prompt, /merge-scouting\.mjs/)
  assert.match(prompt, /11 tab-separated columns/)
  assert.match(prompt, /READY/)
  // The 11-col scouting TSV shape must match modes/scouting.md's definition.
  assert.ok(scouting.includes('11 tab-separated columns'))
})

test('legacy drifted content stays dead', () => {
  for (const banned of [
    'Personalization Plan',   // CV tailoring belongs to modes/pdf.md
    'Interview Plan',         // belongs to modes/interview-prep.md
    'Posting Legitimacy',     // dropped from the scoring model
    'Extracted keywords',     // explicit token waste per modes/scouting.md
    'LLMOps',                 // hardcoded archetype from another user's profile
    'generate-pdf.mjs',       // evaluation NEVER auto-generates PDFs
    'cv-template.html',
    'A-H',                    // the pre-consolidation report format
    'tracker-additions',      // batch evals land in scouting, not applications
  ]) {
    assert.ok(!prompt.includes(banned), `batch prompt must not contain "${banned}"`)
  }
})

test('batch prompt reads the generated CV summary with a documented full-CV fallback', () => {
  // Token-cost lever 3: workers ingest batch/cv-summary.md (generated by
  // scripts/cv-summary.mjs) instead of the full CV — but the fallback to
  // user/cv.md must stay documented so a missing artifact never fails a run.
  assert.match(prompt, /batch\/cv-summary\.md/)
  assert.match(prompt, /scripts\/cv-summary\.mjs/)
  assert.match(prompt, /missing[\s\S]{0,80}user\/cv\.md/i)
})

test('batch prompt documents the unresolved-placeholder contract', () => {
  // Both the batch runner and the frontend pass this file verbatim via
  // --append-system-prompt-file (no per-worker substitution — a byte-identical
  // system prompt is what makes prompt caching work, token-cost lever 4).
  // The bundle must tell workers to take values from the task message.
  assert.match(prompt, /Unresolved placeholders/i)
  assert.match(prompt, /task message/i)
  assert.match(prompt, /verbatim/i)
})

test('batch mode marks verification as unconfirmed', () => {
  assert.match(prompt, /\*\*Verification:\*\* unconfirmed \(batch mode\)/)
})

// ─── Tiered report output (token-cost lever 5) ───────────────────────────────
// Every eval scores fully (score-history row + scouting TSV + dimensional
// table are band-independent), but the PROSE report depth is banded: full
// sections only for Stellar/T1, compact formats below, no file at all for
// Skip/T4. These pins keep batch and interactive evals writing the same
// shapes — a drift here silently reinflates output cost or breaks the
// frontend report parser.

test('band → report depth mapping agrees between the bundle and modes/scouting.md', () => {
  // Bundle: one-line mapping in Step 5.
  assert.match(prompt, /`T1` → Stellar full report/)
  assert.match(prompt, /`T2` → Strong[\s\S]{0,80}short report/)
  assert.match(prompt, /`T3` → Gap & Growth report/)
  assert.match(prompt, /`T4` → Skip \(NO report file\)/)
  // Interactive mode: the same four output behaviors.
  assert.match(scouting, /Generate a \*\*full report\*\*/)
  assert.match(scouting, /Generate a \*\*short summary report\*\*/)
  assert.match(scouting, /Generate a \*\*Gap & Growth Report\*\*/)
  assert.match(scouting, /Do NOT write a report file/)
  // The band definitions themselves live in _shared.md (CF/AF-based).
  for (const band of ['Stellar', 'Strong (CF 8.0–8.9', 'Decent (CF 7.0–7.9',
                      'Pass / Growth Target', 'Skip (CF < 7.0 AND AF < 7.0']) {
    assert.ok(shared.includes(band), `_shared.md defines band "${band}"`)
  }
})

test('compact bands still carry the universal header and the dimensional table', () => {
  // The frontend parser (frontend/src/lib/reportMarkdown.ts) keys on the
  // literal "## Dimensional scoring" heading and the **URL:** header line;
  // both must survive compression in every band that writes a file.
  for (const [name, text] of [['batch prompt', prompt], ['scouting mode', scouting]]) {
    assert.ok(text.includes('## Dimensional scoring'), `${name} names the table heading`)
    assert.ok(text.includes('**URL:**'), `${name} keeps the URL header line`)
  }
  assert.match(prompt, /Body \(all bands\):.*`## Dimensional scoring`/)
  assert.match(scouting, /Always compute the full dimensional table first/)
})

test('skips stay scored — data writes happen for ALL bands including T4', () => {
  // Downstream scripts (peer-rank, calibration-advisor, cv-gap, positioning)
  // read score-history + scouting rows; compression must never drop them.
  assert.match(prompt, /Step 6 — Data writes \(ALL bands, including T4 skips\)/)
  assert.match(scouting, /regardless of tier \(including Tier 4 skips\)/)
  assert.match(scouting, /\*\*Still compute the full dimensional table\*\*/)
})

test('Gap & Growth title, language-wall exception, and no-fabricated-timelines agree', () => {
  for (const [name, text] of [['batch prompt', prompt], ['scouting mode', scouting]]) {
    assert.ok(text.includes('# Gap & Growth:'), `${name} carries the T3 title prefix`)
    assert.match(text, /language.wall/i)
    assert.match(text, /[Nn]o fabricated timelines/)
  }
  // The exception's canonical definition lives in _shared.md.
  assert.match(shared, /language-wall exception/i)
})

test('report naming follows the canonical human-readable convention', () => {
  assert.match(prompt, /reports\/tier-\{N\}\/\{Company\} - \{Role\}\.md/)
  assert.ok(!/reports\/tier-\{N\}\/\{\{REPORT_NUM\}\}/.test(prompt),
    'no sequence-numbered report filenames')
})
